### ISSUE TITLE
API Deprecated

### ISSUE THREAD

**Issue by vitorgamer58** [vitorgamer58/Telegram_Bot_Bovespa#3]
Essa mensagem me dá nos nervos
`TelegramDeprecationWarning: Old Handler API is deprecated`

**Comment by vitorgamer58** [comment]
Atualizado para python-telegram-bot==13.5

```
2021-04-30 19:05:49,954 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\vitor\AppData\Local\Programs\Python\Python38\lib\site-packages\telegram\ext\dispatcher.py", line 447, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\vitor\AppData\Local\Programs\Python\Python38\lib\site-packages\telegram\ext\handler.py", line 160, in handle_update
    return self.callback(update, context)
TypeError: funpricestock() missing 1 required positional argument: 'args'
2021-04-30 19:06:13,886 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\vitor\AppData\Local\Programs\Python\Python38\lib\site-packages\telegram\ext\dispatcher.py", line 447, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\vitor\AppData\Local\Programs\Python\Python38\lib\site-packages\telegram\ext\handler.py", line 160, in handle_update
    return self.callback(update, context)
TypeError: verificagraham() missing 1 required positional argument: 'args'
2021-04-30 19:06:23,700 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\vitor\AppData\Local\Programs\Python\Python38\lib\site-packages\telegram\ext\dispatcher.py", line 447, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\vitor\AppData\Local\Programs\Python\Python38\lib\site-packages\telegram\ext\handler.py", line 160, in handle_update
    return self.callback(update, context)
TypeError: verificafundamentus() missing 1 required positional argument: 'args'
2021-04-30 19:06:26,875 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\vitor\AppData\Local\Programs\Python\Python38\lib\site-packages\telegram\ext\dispatcher.py", line 447, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\vitor\AppData\Local\Programs\Python\Python38\lib\site-packages\telegram\ext\handler.py", line 160, in handle_update
    return self.callback(update, context)
  File "g:\Downloads\Telegram_Bot_Bovespa-graham\src\core.py", line 75, in funbitcoin
    bot.send_message(
AttributeError: 'Update' object has no attribute 'send_message'
```
